name: API

on:
  workflow_dispatch:
  push:
    branches:
     - main
    paths:
     - 'Backend/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build the container App and push it to the ACR 
        uses: azure/container-apps-deploy-action@v1 
        with: 
          appSourcePath: ${{ github.workspace }}/Backend
          dockerfilePath: Dockerfile
          acrName: acrcamposolpocpaltas
          containerAppName: ca-api-camposol-poc-paltas
          resourceGroup: RG-Camposol-POC-Paltas-Peru
          imageToBuild: acrcamposolpocpaltas.azurecr.io/poc-ai-api:latest

     
      - name: Deploy the container app 
        uses: azure/cli@v2
        with: 
          cliversion: 2.30.0
          inlineScript: |
            az containerapp update \
              --name ca-api-camposol-poc-paltas \
              --resource-group RG-Camposol-POC-Paltas-Peru \
              --image acrcamposolpocpaltas.azurecr.io/poc-ai-api:latest \
              --cpu 1.0 \
              --memory 2.0Gi \
              --min-replicas 1 \
              --max-replicas 1 \
              --revision-suffix ${{ steps.get_datetime.outputs.formatted_datetime }} \
              --set-env-vars "FUNCTIONS_WORKER_RUNTIME=python" "AppConfiguration=${{ secrets.APP_CONTIGURATION }}" "AzureWebJobsStorage=${{ secrets.STORAGE_CONNECTION_STRING }}" "StorageConnectionString=${{ secrets.STORAGE_CONNECTION_STRING }}" "AzureWebJobsSecretStorageKeyVaultUri=${{ secrets.KEY_VAULT_URI }}" "APPINSIGHTS_INSTRUMENTATIONKEY=${{ secrets.API_APPINSIGHTS_INSTRUMENTATIONKEY }}" "AzureWebJobsSecretStorageType=keyvault"
